import React from 'react';
import { Badge } from 'react-bootstrap';

export const getCuetDistrictMarksColumns = (columnMapping) => [
  {
    name: 'S.No',
    selector: (row, index) => index + 1,
    sortable: false,
    width: '70px',
    center: true,
  },
  {
    name: columnMapping.Test_Code || 'Test_Code',
    selector: (row) => row.Test_Code,
    sortable: true,
    minWidth: '120px',
  },
  {
    name: columnMapping.BATCHNAME || 'BATCHNAME',
    selector: (row) => row.BATCHNAME,
    sortable: true,
    minWidth: '140px',
  },
  {
    name: columnMapping.District_Name || 'District_Name',
    selector: (row) => row.District_Name,
    sortable: true,
    minWidth: '140px',
  },
  {
    name: columnMapping.ROLLNO || 'Emis_No',
    selector: (row) => row.ROLLNO,
    sortable: true,
    minWidth: '120px',
  },
  {
    name: columnMapping.Candidate_Name || 'Candidate_Name',
    selector: (row) => row.Candidate_Name,
    sortable: true,
    wrap: true,
    minWidth: '180px',
  },
  {
    name: columnMapping.TOTAL || 'Overall_TOTAL',
    selector: (row) => row.TOTAL,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.CORRECT || 'Overall_CORRECT',
    selector: (row) => row.CORRECT,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.WRONG || 'Overall_WRONG',
    selector: (row) => row.WRONG,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.BLANK || 'Overall_BLANK',
    selector: (row) => row.BLANK,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.TOTAL1 || 'Accountancy_TOTAL',
    selector: (row) => row.TOTAL1,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.TOTAL2 || 'Economics_TOTAL',
    selector: (row) => row.TOTAL2,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.TOTAL3 || 'Business_Studies_Commerce_TOTAL',
    selector: (row) => row.TOTAL3,
    sortable: true,
    right: true,
    minWidth: '230px',
  },
  {
    name: columnMapping.TOTAL4 || 'Business_Maths_TOTAL',
    selector: (row) => row.TOTAL4,
    sortable: true,
    right: true,
    minWidth: '190px',
  },
  {
    name: columnMapping.Total_Percentile || 'Total_Percentile',
    selector: (row) => row.Total_Percentile,
    sortable: true,
    right: true,
    minWidth: '170px',
  },
  {
    name: columnMapping.Accountancy_Percentile || 'Accountancy_Percentile',
    selector: (row) => row.Accountancy_Percentile,
    sortable: true,
    right: true,
    minWidth: '200px',
  },
  {
    name: columnMapping.Economics_Percentile || 'Economics_Percentile',
    selector: (row) => row.Economics_Percentile,
    sortable: true,
    right: true,
    minWidth: '190px',
  },
  {
    name:
      columnMapping.Business_Studies_Commerce_Percentile ||
      'Business_Studies_Commerce_Percentile',
    selector: (row) => row.Business_Studies_Commerce_Percentile,
    sortable: true,
    right: true,
    minWidth: '280px',
  },
  {
    name: columnMapping.Business_Maths_Percentile || 'Business_Maths_Percentile',
    selector: (row) => row.Business_Maths_Percentile,
    sortable: true,
    right: true,
    minWidth: '220px',
  },
  {
    name: columnMapping.d_Total_Percentile || 'District_Total_Percentile',
    selector: (row) => row.d_Total_Percentile,
    sortable: true,
    right: true,
    minWidth: '200px',
  },
  {
    name: columnMapping.d_Accountancy_Percentile || 'District_Accountancy_Percentile',
    selector: (row) => row.d_Accountancy_Percentile,
    sortable: true,
    right: true,
    minWidth: '250px',
  },
  {
    name: columnMapping.d_Economics_Percentile || 'District_Economics_Percentile',
    selector: (row) => row.d_Economics_Percentile,
    sortable: true,
    right: true,
    minWidth: '240px',
  },
  {
    name:
      columnMapping.d_Business_Studies_Commerce_Percentile ||
      'District_Business_Studies_Commerce_Percentile',
    selector: (row) => row.d_Business_Studies_Commerce_Percentile,
    sortable: true,
    right: true,
    minWidth: '320px',
  },
  {
    name: columnMapping.d_Business_Maths_Percentile || 'District_Business_Maths_Percentile',
    selector: (row) => row.d_Business_Maths_Percentile,
    sortable: true,
    right: true,
    minWidth: '280px',
  },
  {
    name: 'Overall Rank',
    selector: (row) => row.overallRank,
    sortable: true,
    right: true,
    width: '120px',
    cell: (row) => <Badge bg='primary'>{row.overallRank || '-'}</Badge>,
  },
  {
    name: 'District Rank',
    selector: (row) => row.districtRank,
    sortable: true,
    right: true,
    width: '120px',
    cell: (row) => <Badge bg='success'>{row.districtRank || '-'}</Badge>,
  },
];
