import React from "react";
import { Badge } from "react-bootstrap";

export const getJeeDistrictMarksColumns = (columnMapping) => [
  {
    name: "S.No",
    selector: (row, index) => index + 1,
    sortable: false,
    width: "70px",
    center: true,
  },
  {
    name: columnMapping.Test_Code || "Test_Code",
    selector: (row) => row.Test_Code,
    sortable: true,
    minWidth: "120px",
  },
  {
    name: columnMapping.BATCHNAME || "District_Code",
    selector: (row) => row.BATCHNAME,
    sortable: true,
    minWidth: "140px",
  },
  {
    name: columnMapping.District_Name || "District_Name",
    selector: (row) => row.District_Name,
    sortable: true,
    minWidth: "140px",
  },
  {
    name: columnMapping.ROLLNO || "Emis_No",
    selector: (row) => row.ROLLNO,
    sortable: true,
    minWidth: "100px",
  },
  {
    name: columnMapping.Candidate_Name || "Candidate_Name",
    selector: (row) => row.Candidate_Name,
    sortable: true,
    wrap: true,
    minWidth: "180px",
  },
  {
    name: columnMapping.TOTAL || "Overall_Total",
    selector: (row) => row.TOTAL,
    sortable: true,
    right: true,
    minWidth: "170px",
    cell: (row) => row.TOTAL ?? "-",
  },
  {
    name: columnMapping.CORRECT || "Overall_Correct",
    selector: (row) => row.CORRECT,
    sortable: true,
    right: true,
    minWidth: "170px",
    cell: (row) => row.CORRECT ?? "-",
  },
  {
    name: columnMapping.WRONG || "Overall_Wrong",
    selector: (row) => row.WRONG,
    sortable: true,
    right: true,
    minWidth: "170px",
    cell: (row) => row.WRONG ?? "-",
  },
  {
    name: columnMapping.BLANK || "Overall_Blank",
    selector: (row) => row.BLANK,
    sortable: true,
    right: true,
    minWidth: "170px",
    cell: (row) => row.BLANK ?? "-",
  },
  {
    name: columnMapping.Phy_Tot || "Physics_Total",
    selector: (row) => row.Phy_Tot,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Phy_C || "Physics_Correct",
    selector: (row) => row.Phy_C,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Phy_W || "Physics_Wrong",
    selector: (row) => row.Phy_W,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Phy_B || "Physics_Blank",
    selector: (row) => row.Phy_B,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.che_Tot || "Chemistry_Total",
    selector: (row) => row.che_Tot,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Che_C || "Chemistry_Correct",
    selector: (row) => row.Che_C,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Che_W || "Chemistry_Wrong",
    selector: (row) => row.Che_W,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Che_B || "Chemistry_Blank",
    selector: (row) => row.Che_B,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Mat_Tot || "Maths_Total",
    selector: (row) => row.Mat_Tot,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Mat_C || "Maths_Correct",
    selector: (row) => row.Mat_C,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Mat_W || "Maths_Wrong",
    selector: (row) => row.Mat_W,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Mat_B || "Maths_Blank",
    selector: (row) => row.Mat_B,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Total_Percentile || "Total_Percentile",
    selector: (row) => row.Total_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Phy_Percentile || "Physics_Percentile",
    selector: (row) => row.Phy_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Che_Percentile || "Chemistry_Percentile",
    selector: (row) => row.Che_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Mat_Percentile || "Maths_Percentile",
    selector: (row) => row.Mat_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Total_Percentile || "District_Total_Percentile",
    selector: (row) => row.d_Total_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Phy_Percentile || "District_Physics_Percentile",
    selector: (row) => row.d_Phy_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Che_Percentile || "District_Chemistry_Percentile",
    selector: (row) => row.d_Che_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Mat_Percentile || "District_Maths_Percentile",
    selector: (row) => row.d_Mat_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: "Overall Rank",
    selector: (row) => row.overallRank,
    sortable: true,
    right: true,
    width: "120px",
    cell: (row) => <Badge bg="primary">{row.overallRank || "-"}</Badge>,
  },
  {
    name: "District Rank",
    selector: (row) => row.districtRank,
    sortable: true,
    right: true,
    width: "120px",
    cell: (row) => <Badge bg="success">{row.districtRank || "-"}</Badge>,
  },
];
