import React from "react";
import { Badge } from "react-bootstrap";

export const getNeetDistrictMarksColumns = (columnMapping) => [
  {
    name: "S.No",
    selector: (row, index) => index + 1,
    sortable: false,
    width: "70px",
    center: true,
  },
  {
    name: columnMapping.Test_Code || "Test_Code",
    selector: (row) => row.Test_Code,
    sortable: true,
    minWidth: "120px",
  },
  {
    name: columnMapping.BATCHNAME || "BATCHNAME",
    selector: (row) => row.BATCHNAME,
    sortable: true,
    minWidth: "140px",
  },
  {
    name: columnMapping.District_Name || "District_Name",
    selector: (row) => row.District_Name,
    sortable: true,
    minWidth: "140px",
  },
  {
    name: columnMapping.ROLLNO || "Emis_No",
    selector: (row) => row.ROLLNO,
    sortable: true,
    minWidth: "100px",
  },
  {
    name: columnMapping.Candidate_Name || "Candidate_Name",
    selector: (row) => row.Candidate_Name,
    sortable: true,
    wrap: true,
    minWidth: "180px",
  },
  {
    name: columnMapping.TOTAL || "Overall_TOTAL",
    selector: (row) => row.TOTAL,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.CORRECT || "Overall_CORRECT",
    selector: (row) => row.CORRECT,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.WRONG || "Overall_WRONG",
    selector: (row) => row.WRONG,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.BLANK || "Overall_BLANK",
    selector: (row) => row.BLANK,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.TOTAL1 || "Physics_TOTAL",
    selector: (row) => row.TOTAL1,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.CORRECT1 || "Physics_CORRECT",
    selector: (row) => row.CORRECT1,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.WRONG1 || "Physics_WRONG",
    selector: (row) => row.WRONG1,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.BLANK1 || "Physics_BLANK",
    selector: (row) => row.BLANK1,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.TOTAL2 || "Chemistry_TOTAL",
    selector: (row) => row.TOTAL2,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.CORRECT2 || "Chemistry_CORRECT",
    selector: (row) => row.CORRECT2,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.WRONG2 || "Chemistry_WRONG",
    selector: (row) => row.WRONG2,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.BLANK2 || "Chemistry_BLANK",
    selector: (row) => row.BLANK2,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.TOTAL3 || "Botany_TOTAL",
    selector: (row) => row.TOTAL3,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.CORRECT3 || "Botany_CORRECT",
    selector: (row) => row.CORRECT3,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.WRONG3 || "Botany_WRONG",
    selector: (row) => row.WRONG3,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.BLANK3 || "Botany_BLANK",
    selector: (row) => row.BLANK3,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.TOTAL4 || "Zoology_TOTAL",
    selector: (row) => row.TOTAL4,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.CORRECT4 || "Zoology_CORRECT",
    selector: (row) => row.CORRECT4,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.WRONG4 || "Zoology_WRONG",
    selector: (row) => row.WRONG4,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.BLANK4 || "Zoology_BLANK",
    selector: (row) => row.BLANK4,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Total_Percentile || "Total_Percentile",
    selector: (row) => row.Total_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Phy_Percentile || "Physics_Percentile",
    selector: (row) => row.Phy_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Che_Percentile || "Chemistry_Percentile",
    selector: (row) => row.Che_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Bot_Percentile || "Botany_Percentile",
    selector: (row) => row.Bot_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.Zoo_Percentile || "Zoology_Percentile",
    selector: (row) => row.Zoo_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Total_Percentile || "District_Total_Percentile",
    selector: (row) => row.d_Total_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Phy_Percentile || "District_Physics_Percentile",
    selector: (row) => row.d_Phy_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Che_Percentile || "District_Chemistry_Percentile",
    selector: (row) => row.d_Che_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Bot_Percentile || "District_Botany_Percentile",
    selector: (row) => row.d_Bot_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: columnMapping.d_Zoo_Percentile || "District_Zoology_Percentile",
    selector: (row) => row.d_Zoo_Percentile,
    sortable: true,
    right: true,
    minWidth: "170px",
  },
  {
    name: "Overall Rank",
    selector: (row) => row.overallRank,
    sortable: true,
    right: true,
    width: "120px",
    cell: (row) => <Badge bg="primary">{row.overallRank || "-"}</Badge>,
  },
  {
    name: "District Rank",
    selector: (row) => row.districtRank,
    sortable: true,
    right: true,
    width: "120px",
    cell: (row) => <Badge bg="success">{row.districtRank || "-"}</Badge>,
  },
];
