import React from "react";

const percentileCell = (value) => (value != null ? Number(value).toFixed(4) : '-');

export const getSpokenEnglishDistrictMarksColumns = () => [
  { name: "S.No", selector: (row, index) => index + 1, sortable: false, width: "70px", center: true },
  { name: "Test Code", selector: (row) => row.Test_Code, sortable: true, minWidth: "120px" },
  { name: "District Code", selector: (row) => row.BATCHNAME, sortable: true, minWidth: "130px" },
  { name: "District Name", selector: (row) => row.District_Name, sortable: true, minWidth: "140px" },
  { name: "EMIS No", selector: (row) => row.ROLLNO, sortable: true, minWidth: "110px" },
  { name: "Candidate Name", selector: (row) => row.Candidate_Name, sortable: true, wrap: true, minWidth: "180px" },
  { name: "Overall Total", selector: (row) => row.TOTAL, sortable: true, right: true, minWidth: "130px" },
  { name: "Overall Correct", selector: (row) => row.CORRECT, sortable: true, right: true, minWidth: "130px" },
  { name: "Overall Wrong", selector: (row) => row.WRONG, sortable: true, right: true, minWidth: "130px" },
  { name: "Overall Blank", selector: (row) => row.BLANK, sortable: true, right: true, minWidth: "130px" },
  { name: "Listening Total", selector: (row) => row.TOTAL1, sortable: true, right: true, minWidth: "140px" },
  { name: "Listening Correct", selector: (row) => row.CORRECT1, sortable: true, right: true, minWidth: "150px" },
  { name: "Listening Wrong", selector: (row) => row.WRONG1, sortable: true, right: true, minWidth: "140px" },
  { name: "Listening Blank", selector: (row) => row.BLANK1, sortable: true, right: true, minWidth: "140px" },
  { name: "Speaking Total", selector: (row) => row.TOTAL2, sortable: true, right: true, minWidth: "140px" },
  { name: "Speaking Correct", selector: (row) => row.CORRECT2, sortable: true, right: true, minWidth: "150px" },
  { name: "Speaking Wrong", selector: (row) => row.WRONG2, sortable: true, right: true, minWidth: "140px" },
  { name: "Speaking Blank", selector: (row) => row.BLANK2, sortable: true, right: true, minWidth: "140px" },
  { name: "Reading Total", selector: (row) => row.TOTAL3, sortable: true, right: true, minWidth: "140px" },
  { name: "Reading Correct", selector: (row) => row.CORRECT3, sortable: true, right: true, minWidth: "150px" },
  { name: "Reading Wrong", selector: (row) => row.WRONG3, sortable: true, right: true, minWidth: "140px" },
  { name: "Reading Blank", selector: (row) => row.BLANK3, sortable: true, right: true, minWidth: "140px" },
  { name: "Writing Total", selector: (row) => row.TOTAL4, sortable: true, right: true, minWidth: "140px" },
  { name: "Writing Correct", selector: (row) => row.CORRECT4, sortable: true, right: true, minWidth: "150px" },
  { name: "Writing Wrong", selector: (row) => row.WRONG4, sortable: true, right: true, minWidth: "140px" },
  { name: "Writing Blank", selector: (row) => row.BLANK4, sortable: true, right: true, minWidth: "140px" },
  { name: "Listening Percentile", selector: (row) => row.listeningPerecentile, sortable: true, right: true, minWidth: "170px", cell: (row) => percentileCell(row.listeningPerecentile) },
  { name: "Speaking Percentile", selector: (row) => row.speakingPerecentile, sortable: true, right: true, minWidth: "170px", cell: (row) => percentileCell(row.speakingPerecentile) },
  { name: "Reading Percentile", selector: (row) => row.readingPercentile, sortable: true, right: true, minWidth: "170px", cell: (row) => percentileCell(row.readingPercentile) },
  { name: "Writing Percentile", selector: (row) => row.writingPercetile, sortable: true, right: true, minWidth: "170px", cell: (row) => percentileCell(row.writingPercetile) },
  { name: "Total Percentile", selector: (row) => row.Total_Percentile, sortable: true, right: true, minWidth: "150px", cell: (row) => percentileCell(row.Total_Percentile) },
  { name: "District Listening Percentile", selector: (row) => row.d_listeningPerecentile, sortable: true, right: true, minWidth: "210px", cell: (row) => percentileCell(row.d_listeningPerecentile) },
  { name: "District Speaking Percentile", selector: (row) => row.d_speakingPerecentile, sortable: true, right: true, minWidth: "210px", cell: (row) => percentileCell(row.d_speakingPerecentile) },
  { name: "District Reading Percentile", selector: (row) => row.d_readingPercentile, sortable: true, right: true, minWidth: "210px", cell: (row) => percentileCell(row.d_readingPercentile) },
  { name: "District Writing Percentile", selector: (row) => row.d_writingPercetile, sortable: true, right: true, minWidth: "210px", cell: (row) => percentileCell(row.d_writingPercetile) },
  { name: "District Total Percentile", selector: (row) => row.d_Total_Percentile, sortable: true, right: true, minWidth: "180px", cell: (row) => percentileCell(row.d_Total_Percentile) },
];
