const getLabel = (mapping, key, fallback) => mapping[key] || fallback;
const percentileCell = (value) => (value != null ? Number(value).toFixed(4) : '-');

export const getHumanitiesMarksColumns = ({ columnMapping, selectedDistrict }) => [
  { name: 'S.No', selector: (row, index) => index + 1, sortable: false, width: '70px', center: true },
  { name: getLabel(columnMapping, 'Test_Code', 'Test Code'), selector: (row) => row.Test_Code, sortable: true, minWidth: '120px' },
  { name: getLabel(columnMapping, 'BATCHNAME', 'District Code'), selector: (row) => row.BATCHNAME, sortable: true, minWidth: '140px' },
  { name: 'District Name', selector: (row) => row.District_Name, sortable: true, minWidth: '150px' },
  { name: getLabel(columnMapping, 'ROLLNO', 'EMIS No'), selector: (row) => row.ROLLNO, sortable: true, minWidth: '110px' },
  { name: getLabel(columnMapping, 'Candidate_Name', 'Candidate Name'), selector: (row) => row.Candidate_Name, sortable: true, wrap: true, minWidth: '180px' },
  { name: getLabel(columnMapping, 'TOTAL', 'Overall Total'), selector: (row) => row.TOTAL, sortable: true, right: true, minWidth: '130px', cell: (row) => row.TOTAL ?? '-' },
  { name: getLabel(columnMapping, 'CORRECT', 'Overall Correct'), selector: (row) => row.CORRECT, sortable: true, right: true, minWidth: '130px', cell: (row) => row.CORRECT ?? '-' },
  { name: getLabel(columnMapping, 'WRONG', 'Overall Wrong'), selector: (row) => row.WRONG, sortable: true, right: true, minWidth: '130px', cell: (row) => row.WRONG ?? '-' },
  { name: getLabel(columnMapping, 'BLANK', 'Overall Blank'), selector: (row) => row.BLANK, sortable: true, right: true, minWidth: '130px', cell: (row) => row.BLANK ?? '-' },
  { name: getLabel(columnMapping, 'TOTAL1', 'Economics Total'), selector: (row) => row.TOTAL1, sortable: true, right: true, minWidth: '150px', cell: (row) => row.TOTAL1 ?? '-' },
  { name: getLabel(columnMapping, 'CORRECT1', 'Economics Correct'), selector: (row) => row.CORRECT1, sortable: true, right: true, minWidth: '170px', cell: (row) => row.CORRECT1 ?? '-' },
  { name: getLabel(columnMapping, 'WRONG1', 'Economics Wrong'), selector: (row) => row.WRONG1, sortable: true, right: true, minWidth: '160px', cell: (row) => row.WRONG1 ?? '-' },
  { name: getLabel(columnMapping, 'BLANK1', 'Economics Blank'), selector: (row) => row.BLANK1, sortable: true, right: true, minWidth: '160px', cell: (row) => row.BLANK1 ?? '-' },
  { name: getLabel(columnMapping, 'TOTAL2', 'History Total'), selector: (row) => row.TOTAL2, sortable: true, right: true, minWidth: '130px', cell: (row) => row.TOTAL2 ?? '-' },
  { name: getLabel(columnMapping, 'CORRECT2', 'History Correct'), selector: (row) => row.CORRECT2, sortable: true, right: true, minWidth: '150px', cell: (row) => row.CORRECT2 ?? '-' },
  { name: getLabel(columnMapping, 'WRONG2', 'History Wrong'), selector: (row) => row.WRONG2, sortable: true, right: true, minWidth: '140px', cell: (row) => row.WRONG2 ?? '-' },
  { name: getLabel(columnMapping, 'BLANK2', 'History Blank'), selector: (row) => row.BLANK2, sortable: true, right: true, minWidth: '140px', cell: (row) => row.BLANK2 ?? '-' },
  { name: getLabel(columnMapping, 'TOTAL3', 'Political Science Total'), selector: (row) => row.TOTAL3, sortable: true, right: true, minWidth: '190px', cell: (row) => row.TOTAL3 ?? '-' },
  { name: getLabel(columnMapping, 'CORRECT3', 'Political Science Correct'), selector: (row) => row.CORRECT3, sortable: true, right: true, minWidth: '210px', cell: (row) => row.CORRECT3 ?? '-' },
  { name: getLabel(columnMapping, 'WRONG3', 'Political Science Wrong'), selector: (row) => row.WRONG3, sortable: true, right: true, minWidth: '200px', cell: (row) => row.WRONG3 ?? '-' },
  { name: getLabel(columnMapping, 'BLANK3', 'Political Science Blank'), selector: (row) => row.BLANK3, sortable: true, right: true, minWidth: '200px', cell: (row) => row.BLANK3 ?? '-' },
  { name: getLabel(columnMapping, 'TOTAL4', 'Geography Total'), selector: (row) => row.TOTAL4, sortable: true, right: true, minWidth: '140px', cell: (row) => row.TOTAL4 ?? '-' },
  { name: getLabel(columnMapping, 'CORRECT4', 'Geography Correct'), selector: (row) => row.CORRECT4, sortable: true, right: true, minWidth: '160px', cell: (row) => row.CORRECT4 ?? '-' },
  { name: getLabel(columnMapping, 'WRONG4', 'Geography Wrong'), selector: (row) => row.WRONG4, sortable: true, right: true, minWidth: '150px', cell: (row) => row.WRONG4 ?? '-' },
  { name: getLabel(columnMapping, 'BLANK4', 'Geography Blank'), selector: (row) => row.BLANK4, sortable: true, right: true, minWidth: '150px', cell: (row) => row.BLANK4 ?? '-' },
  { name: 'Total Percentile', selector: (row) => row.Total_Percentile, sortable: true, right: true, minWidth: '150px', cell: (row) => percentileCell(row.Total_Percentile) },
  { name: 'Economics Percentile', selector: (row) => row.Economics_Percentile, sortable: true, right: true, minWidth: '170px', cell: (row) => percentileCell(row.Economics_Percentile) },
  { name: 'History Percentile', selector: (row) => row.History_Percentile, sortable: true, right: true, minWidth: '150px', cell: (row) => percentileCell(row.History_Percentile) },
  { name: 'Political Science Percentile', selector: (row) => row.Political_Science_Percentile, sortable: true, right: true, minWidth: '210px', cell: (row) => percentileCell(row.Political_Science_Percentile) },
  { name: 'Geography Percentile', selector: (row) => row.Geography_Percentile, sortable: true, right: true, minWidth: '160px', cell: (row) => percentileCell(row.Geography_Percentile) },
  ...(selectedDistrict ? [
    { name: 'District Total Percentile', selector: (row) => row.d_Total_Percentile, sortable: true, right: true, minWidth: '180px', cell: (row) => percentileCell(row.d_Total_Percentile) },
    { name: 'District Economics Percentile', selector: (row) => row.d_Economics_Percentile, sortable: true, right: true, minWidth: '190px', cell: (row) => percentileCell(row.d_Economics_Percentile) },
    { name: 'District History Percentile', selector: (row) => row.d_History_Percentile, sortable: true, right: true, minWidth: '180px', cell: (row) => percentileCell(row.d_History_Percentile) },
    { name: 'District Political Science Percentile', selector: (row) => row.d_Political_Science_Percentile, sortable: true, right: true, minWidth: '240px', cell: (row) => percentileCell(row.d_Political_Science_Percentile) },
    { name: 'District Geography Percentile', selector: (row) => row.d_Geography_Percentile, sortable: true, right: true, minWidth: '200px', cell: (row) => percentileCell(row.d_Geography_Percentile) },
  ] : []),
];
