import React from "react";

export const getSpokenEnglishMarksColumns = ({ selectedDistrict }) => [
  { name: "S.No", selector: (row, index) => index + 1, sortable: false, width: "70px", center: true },
  { name: "Test Code", selector: (row) => row.Test_Code, sortable: true, minWidth: "120px" },
  { name: "District Code", selector: (row) => row.BATCHNAME, sortable: true, minWidth: "140px" },
  { name: "District Name", selector: (row) => row.District_Name, sortable: true, minWidth: "140px" },
  { name: "EMIS No", selector: (row) => row.ROLLNO, sortable: true, minWidth: "110px" },
  { name: "Candidate Name", selector: (row) => row.Candidate_Name, sortable: true, wrap: true, minWidth: "180px" },
  { name: "Overall Total", selector: (row) => row.TOTAL, sortable: true, right: true, minWidth: "130px" },
  { name: "Overall Correct", selector: (row) => row.CORRECT, sortable: true, right: true, minWidth: "130px" },
  { name: "Overall Wrong", selector: (row) => row.WRONG, sortable: true, right: true, minWidth: "120px" },
  { name: "Overall Blank", selector: (row) => row.BLANK, sortable: true, right: true, minWidth: "120px" },
  { name: "Listening Total", selector: (row) => row.TOTAL1, sortable: true, right: true, minWidth: "130px" },
  { name: "Listening Correct", selector: (row) => row.CORRECT1, sortable: true, right: true, minWidth: "140px" },
  { name: "Listening Wrong", selector: (row) => row.WRONG1, sortable: true, right: true, minWidth: "130px" },
  { name: "Listening Blank", selector: (row) => row.BLANK1, sortable: true, right: true, minWidth: "130px" },
  { name: "Speaking Total", selector: (row) => row.TOTAL2, sortable: true, right: true, minWidth: "130px" },
  { name: "Speaking Correct", selector: (row) => row.CORRECT2, sortable: true, right: true, minWidth: "140px" },
  { name: "Speaking Wrong", selector: (row) => row.WRONG2, sortable: true, right: true, minWidth: "130px" },
  { name: "Speaking Blank", selector: (row) => row.BLANK2, sortable: true, right: true, minWidth: "130px" },
  { name: "Reading Total", selector: (row) => row.TOTAL3, sortable: true, right: true, minWidth: "130px" },
  { name: "Reading Correct", selector: (row) => row.CORRECT3, sortable: true, right: true, minWidth: "140px" },
  { name: "Reading Wrong", selector: (row) => row.WRONG3, sortable: true, right: true, minWidth: "130px" },
  { name: "Reading Blank", selector: (row) => row.BLANK3, sortable: true, right: true, minWidth: "130px" },
  { name: "Writing Total", selector: (row) => row.TOTAL4, sortable: true, right: true, minWidth: "130px" },
  { name: "Writing Correct", selector: (row) => row.CORRECT4, sortable: true, right: true, minWidth: "140px" },
  { name: "Writing Wrong", selector: (row) => row.WRONG4, sortable: true, right: true, minWidth: "130px" },
  { name: "Writing Blank", selector: (row) => row.BLANK4, sortable: true, right: true, minWidth: "130px" },
  { name: "Total Percentile", selector: (row) => row.Total_Percentile, sortable: true, right: true, minWidth: "150px", cell: (row) => row.Total_Percentile != null ? Number(row.Total_Percentile).toFixed(4) : "-" },
  { name: "Listening Percentile", selector: (row) => row.listeningPerecentile, sortable: true, right: true, minWidth: "170px", cell: (row) => row.listeningPerecentile != null ? Number(row.listeningPerecentile).toFixed(4) : "-" },
  { name: "Speaking Percentile", selector: (row) => row.speakingPerecentile, sortable: true, right: true, minWidth: "170px", cell: (row) => row.speakingPerecentile != null ? Number(row.speakingPerecentile).toFixed(4) : "-" },
  { name: "Reading Percentile", selector: (row) => row.readingPercentile, sortable: true, right: true, minWidth: "170px", cell: (row) => row.readingPercentile != null ? Number(row.readingPercentile).toFixed(4) : "-" },
  { name: "Writing Percentile", selector: (row) => row.writingPercetile, sortable: true, right: true, minWidth: "170px", cell: (row) => row.writingPercetile != null ? Number(row.writingPercetile).toFixed(4) : "-" },
  ...(selectedDistrict
    ? [
        { name: "District Total Percentile", selector: (row) => row.d_Total_Percentile, sortable: true, right: true, minWidth: "180px", cell: (row) => row.d_Total_Percentile != null ? Number(row.d_Total_Percentile).toFixed(4) : "-" },
        { name: "District Listening Percentile", selector: (row) => row.d_listeningPerecentile, sortable: true, right: true, minWidth: "210px", cell: (row) => row.d_listeningPerecentile != null ? Number(row.d_listeningPerecentile).toFixed(4) : "-" },
        { name: "District Speaking Percentile", selector: (row) => row.d_speakingPerecentile, sortable: true, right: true, minWidth: "210px", cell: (row) => row.d_speakingPerecentile != null ? Number(row.d_speakingPerecentile).toFixed(4) : "-" },
        { name: "District Reading Percentile", selector: (row) => row.d_readingPercentile, sortable: true, right: true, minWidth: "210px", cell: (row) => row.d_readingPercentile != null ? Number(row.d_readingPercentile).toFixed(4) : "-" },
        { name: "District Writing Percentile", selector: (row) => row.d_writingPercetile, sortable: true, right: true, minWidth: "210px", cell: (row) => row.d_writingPercetile != null ? Number(row.d_writingPercetile).toFixed(4) : "-" },
      ]
    : []),
];
